//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5420.
// 
#pragma warning disable 1591

namespace LoginForm.CCMAlogin {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthenticationServiceSoap", Namespace="http://Authentication.CCMA.Applications.Nortel.com")]
    public partial class AuthenticationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AuthenticateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateCCMA_UserOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogoutTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSSOCookieNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback BasicTestOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateAgentProfileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AuthenticationService() {
            this.Url = global::LoginForm.Properties.Settings.Default.LoginForm_CCMAlogin_AuthenticationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AuthenticateUserCompletedEventHandler AuthenticateUserCompleted;
        
        /// <remarks/>
        public event AuthenticateCCMA_UserCompletedEventHandler AuthenticateCCMA_UserCompleted;
        
        /// <remarks/>
        public event AuthenticateTokenCompletedEventHandler AuthenticateTokenCompleted;
        
        /// <remarks/>
        public event LogoutTokenCompletedEventHandler LogoutTokenCompleted;
        
        /// <remarks/>
        public event GetSSOCookieNameCompletedEventHandler GetSSOCookieNameCompleted;
        
        /// <remarks/>
        public event BasicTestCompletedEventHandler BasicTestCompleted;
        
        /// <remarks/>
        public event CreateAgentProfileCompletedEventHandler CreateAgentProfileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Authentication.CCMA.Applications.Nortel.com/AuthenticateUser", RequestNamespace="http://Authentication.CCMA.Applications.Nortel.com", ResponseNamespace="http://Authentication.CCMA.Applications.Nortel.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AuthenticateUser(string Username, string Password, out string SSOToken, out string strErrMsg) {
            object[] results = this.Invoke("AuthenticateUser", new object[] {
                        Username,
                        Password});
            SSOToken = ((string)(results[1]));
            strErrMsg = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateUserAsync(string Username, string Password) {
            this.AuthenticateUserAsync(Username, Password, null);
        }
        
        /// <remarks/>
        public void AuthenticateUserAsync(string Username, string Password, object userState) {
            if ((this.AuthenticateUserOperationCompleted == null)) {
                this.AuthenticateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateUserOperationCompleted);
            }
            this.InvokeAsync("AuthenticateUser", new object[] {
                        Username,
                        Password}, this.AuthenticateUserOperationCompleted, userState);
        }
        
        private void OnAuthenticateUserOperationCompleted(object arg) {
            if ((this.AuthenticateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateUserCompleted(this, new AuthenticateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Authentication.CCMA.Applications.Nortel.com/AuthenticateCCMA_User", RequestNamespace="http://Authentication.CCMA.Applications.Nortel.com", ResponseNamespace="http://Authentication.CCMA.Applications.Nortel.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AuthenticateCCMA_User(string Username, string Password, string Component, out string xmlParameterList, out string strErrMsg) {
            object[] results = this.Invoke("AuthenticateCCMA_User", new object[] {
                        Username,
                        Password,
                        Component});
            xmlParameterList = ((string)(results[1]));
            strErrMsg = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateCCMA_UserAsync(string Username, string Password, string Component) {
            this.AuthenticateCCMA_UserAsync(Username, Password, Component, null);
        }
        
        /// <remarks/>
        public void AuthenticateCCMA_UserAsync(string Username, string Password, string Component, object userState) {
            if ((this.AuthenticateCCMA_UserOperationCompleted == null)) {
                this.AuthenticateCCMA_UserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateCCMA_UserOperationCompleted);
            }
            this.InvokeAsync("AuthenticateCCMA_User", new object[] {
                        Username,
                        Password,
                        Component}, this.AuthenticateCCMA_UserOperationCompleted, userState);
        }
        
        private void OnAuthenticateCCMA_UserOperationCompleted(object arg) {
            if ((this.AuthenticateCCMA_UserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateCCMA_UserCompleted(this, new AuthenticateCCMA_UserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Authentication.CCMA.Applications.Nortel.com/AuthenticateToken", RequestNamespace="http://Authentication.CCMA.Applications.Nortel.com", ResponseNamespace="http://Authentication.CCMA.Applications.Nortel.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AuthenticateToken(string SSOToken, out string strErrMsg) {
            object[] results = this.Invoke("AuthenticateToken", new object[] {
                        SSOToken});
            strErrMsg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateTokenAsync(string SSOToken) {
            this.AuthenticateTokenAsync(SSOToken, null);
        }
        
        /// <remarks/>
        public void AuthenticateTokenAsync(string SSOToken, object userState) {
            if ((this.AuthenticateTokenOperationCompleted == null)) {
                this.AuthenticateTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateTokenOperationCompleted);
            }
            this.InvokeAsync("AuthenticateToken", new object[] {
                        SSOToken}, this.AuthenticateTokenOperationCompleted, userState);
        }
        
        private void OnAuthenticateTokenOperationCompleted(object arg) {
            if ((this.AuthenticateTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateTokenCompleted(this, new AuthenticateTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Authentication.CCMA.Applications.Nortel.com/LogoutToken", RequestNamespace="http://Authentication.CCMA.Applications.Nortel.com", ResponseNamespace="http://Authentication.CCMA.Applications.Nortel.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool LogoutToken(string SSOToken, out string strErrMsg) {
            object[] results = this.Invoke("LogoutToken", new object[] {
                        SSOToken});
            strErrMsg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LogoutTokenAsync(string SSOToken) {
            this.LogoutTokenAsync(SSOToken, null);
        }
        
        /// <remarks/>
        public void LogoutTokenAsync(string SSOToken, object userState) {
            if ((this.LogoutTokenOperationCompleted == null)) {
                this.LogoutTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutTokenOperationCompleted);
            }
            this.InvokeAsync("LogoutToken", new object[] {
                        SSOToken}, this.LogoutTokenOperationCompleted, userState);
        }
        
        private void OnLogoutTokenOperationCompleted(object arg) {
            if ((this.LogoutTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoutTokenCompleted(this, new LogoutTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Authentication.CCMA.Applications.Nortel.com/GetSSOCookieName", RequestNamespace="http://Authentication.CCMA.Applications.Nortel.com", ResponseNamespace="http://Authentication.CCMA.Applications.Nortel.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSSOCookieName(out string strErrMsg) {
            object[] results = this.Invoke("GetSSOCookieName", new object[0]);
            strErrMsg = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSSOCookieNameAsync() {
            this.GetSSOCookieNameAsync(null);
        }
        
        /// <remarks/>
        public void GetSSOCookieNameAsync(object userState) {
            if ((this.GetSSOCookieNameOperationCompleted == null)) {
                this.GetSSOCookieNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSSOCookieNameOperationCompleted);
            }
            this.InvokeAsync("GetSSOCookieName", new object[0], this.GetSSOCookieNameOperationCompleted, userState);
        }
        
        private void OnGetSSOCookieNameOperationCompleted(object arg) {
            if ((this.GetSSOCookieNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSSOCookieNameCompleted(this, new GetSSOCookieNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Authentication.CCMA.Applications.Nortel.com/BasicTest", RequestNamespace="http://Authentication.CCMA.Applications.Nortel.com", ResponseNamespace="http://Authentication.CCMA.Applications.Nortel.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BasicTest(string text) {
            object[] results = this.Invoke("BasicTest", new object[] {
                        text});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BasicTestAsync(string text) {
            this.BasicTestAsync(text, null);
        }
        
        /// <remarks/>
        public void BasicTestAsync(string text, object userState) {
            if ((this.BasicTestOperationCompleted == null)) {
                this.BasicTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBasicTestOperationCompleted);
            }
            this.InvokeAsync("BasicTest", new object[] {
                        text}, this.BasicTestOperationCompleted, userState);
        }
        
        private void OnBasicTestOperationCompleted(object arg) {
            if ((this.BasicTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BasicTestCompleted(this, new BasicTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Authentication.CCMA.Applications.Nortel.com/CreateAgentProfile", RequestNamespace="http://Authentication.CCMA.Applications.Nortel.com", ResponseNamespace="http://Authentication.CCMA.Applications.Nortel.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateAgentProfile(string strAgentName, string strPassword, string strToken, string strAgentHostURL, out string strResult) {
            object[] results = this.Invoke("CreateAgentProfile", new object[] {
                        strAgentName,
                        strPassword,
                        strToken,
                        strAgentHostURL});
            strResult = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAgentProfileAsync(string strAgentName, string strPassword, string strToken, string strAgentHostURL) {
            this.CreateAgentProfileAsync(strAgentName, strPassword, strToken, strAgentHostURL, null);
        }
        
        /// <remarks/>
        public void CreateAgentProfileAsync(string strAgentName, string strPassword, string strToken, string strAgentHostURL, object userState) {
            if ((this.CreateAgentProfileOperationCompleted == null)) {
                this.CreateAgentProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAgentProfileOperationCompleted);
            }
            this.InvokeAsync("CreateAgentProfile", new object[] {
                        strAgentName,
                        strPassword,
                        strToken,
                        strAgentHostURL}, this.CreateAgentProfileOperationCompleted, userState);
        }
        
        private void OnCreateAgentProfileOperationCompleted(object arg) {
            if ((this.CreateAgentProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAgentProfileCompleted(this, new CreateAgentProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void AuthenticateUserCompletedEventHandler(object sender, AuthenticateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string SSOToken {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string strErrMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void AuthenticateCCMA_UserCompletedEventHandler(object sender, AuthenticateCCMA_UserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateCCMA_UserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateCCMA_UserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string xmlParameterList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string strErrMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void AuthenticateTokenCompletedEventHandler(object sender, AuthenticateTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strErrMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void LogoutTokenCompletedEventHandler(object sender, LogoutTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogoutTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogoutTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strErrMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetSSOCookieNameCompletedEventHandler(object sender, GetSSOCookieNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSSOCookieNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSSOCookieNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strErrMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void BasicTestCompletedEventHandler(object sender, BasicTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BasicTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BasicTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void CreateAgentProfileCompletedEventHandler(object sender, CreateAgentProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateAgentProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateAgentProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591